version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ~/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: 'GMT'
      PGTZ: 'GMT'
  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./docker/backend/Dockerfile.dev
  #   ports:
  #     - 8080:8080
  #   environment:
  #     DATABASE_DRIVER_NAME: ${DATABASE_DRIVER_NAME}
  #     DATABASE_HOST: ${DATABASE_HOST}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DATABASE_NAME: ${POSTGRES_DATABASE_NAME}
  #     GOPATH: ${GOPATH}
  #   depends_on:
  #     - db